version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./Backend:/var/www/html   # Đảm bảo ./www tồn tại và chứa các file PHP của bạn
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goatgym
      MYSQL_USER: admin
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    restart: always
    ports:
      - 8081:80   # Sử dụng cổng khác cho phpMyAdmin để tránh xung đột
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goatgym
      MYSQL_USER: admin
      MYSQL_PASSWORD: rootpassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
